import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { FinancialMetrics } from "@/hooks/useFinancialData";
import type { RegulationInsights } from "@/hooks/useRegulationInsights";

export interface OfficialDocumentConfig {
  businessName: string;
  panNumber?: string;
  vatNumber?: string;
  registrationNumber?: string;
  address?: string;
  fiscalYear?: string;
  period?: string;
  signatoryName?: string;
  signatoryDesignation?: string;
}

const formatCurrency = (amount: number): string => {
  return `NPR ${amount.toLocaleString("en-NP", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
};

const formatDate = (date: Date): string => {
  return date.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
};

const addOfficialHeader = (
  doc: jsPDF,
  title: string,
  subtitle: string,
  config: OfficialDocumentConfig
) => {
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header background
  doc.setFillColor(26, 35, 126);
  doc.rect(0, 0, pageWidth, 55, "F");

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(title, pageWidth / 2, 22, { align: "center" });

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(subtitle, pageWidth / 2, 32, { align: "center" });

  // Business info
  if (config.businessName) {
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(config.businessName, pageWidth / 2, 45, { align: "center" });
  }

  return 65;
};

const addBusinessInfoSection = (
  doc: jsPDF,
  yPos: number,
  config: OfficialDocumentConfig
): number => {
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.5);
  doc.rect(20, yPos, pageWidth - 40, 35);

  doc.setTextColor(80, 80, 80);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");

  const leftX = 25;
  const rightX = pageWidth / 2 + 10;

  doc.text(`Business Name: ${config.businessName || "N/A"}`, leftX, yPos + 10);
  doc.text(
    `PAN Number: ${config.panNumber || "________________"}`,
    leftX,
    yPos + 20
  );
  doc.text(
    `Address: ${config.address || "________________"}`,
    leftX,
    yPos + 30
  );

  doc.text(
    `VAT Number: ${config.vatNumber || "________________"}`,
    rightX,
    yPos + 10
  );
  doc.text(
    `Registration No: ${config.registrationNumber || "________________"}`,
    rightX,
    yPos + 20
  );
  doc.text(
    `Fiscal Year: ${config.fiscalYear || getCurrentFiscalYear()}`,
    rightX,
    yPos + 30
  );

  return yPos + 45;
};

const addSignatureSection = (
  doc: jsPDF,
  yPos: number,
  config: OfficialDocumentConfig
): void => {
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setDrawColor(100, 100, 100);
  doc.setLineWidth(0.3);

  // Left signature
  doc.line(25, yPos + 20, 85, yPos + 20);
  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  doc.text("Prepared By", 45, yPos + 28, { align: "center" });

  // Right signature
  doc.line(pageWidth - 85, yPos + 20, pageWidth - 25, yPos + 20);
  doc.text(
    config.signatoryDesignation || "Authorized Signatory",
    pageWidth - 55,
    yPos + 28,
    { align: "center" }
  );
  if (config.signatoryName) {
    doc.text(config.signatoryName, pageWidth - 55, yPos + 36, {
      align: "center",
    });
  }

  // Date
  doc.text(`Date: ${formatDate(new Date())}`, pageWidth / 2, yPos + 28, {
    align: "center",
  });

  // Stamp area
  doc.setDrawColor(200, 200, 200);
  doc.setLineDashPattern([2, 2], 0);
  doc.rect(pageWidth / 2 - 20, yPos + 35, 40, 25);
  doc.setFontSize(8);
  doc.setTextColor(180, 180, 180);
  doc.text("Company Stamp", pageWidth / 2, yPos + 50, { align: "center" });
  doc.setLineDashPattern([], 0);
};

const addFooter = (doc: jsPDF, documentType: string) => {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${pageCount} | ${documentType} | Generated by Arthiq`,
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    );
  }
};

const getCurrentFiscalYear = (): string => {
  const now = new Date();
  const year = now.getFullYear();
  const month = now.getMonth();
  // Nepal fiscal year runs from Shrawan (mid-July) to Ashadh (mid-July)
  if (month >= 6) {
    // July onwards
    return `${year}/${year + 1}`;
  }
  return `${year - 1}/${year}`;
};

// VAT Return Form (similar to IRD format)
export const generateVATReturnForm = (
  metrics: FinancialMetrics,
  config: OfficialDocumentConfig
): jsPDF => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  let yPos = addOfficialHeader(
    doc,
    "VAT RETURN FORM",
    "As per Inland Revenue Department Format",
    config
  );
  yPos = addBusinessInfoSection(doc, yPos, config);

  // Period
  doc.setTextColor(26, 35, 126);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(`Return Period: ${config.period || "Monthly"}`, 20, yPos);
  yPos += 15;

  const vatRate = 0.13;
  const outputVAT = metrics.totalRevenue * vatRate;
  const inputVAT = metrics.totalExpenses * vatRate;
  const netVAT = outputVAT - inputVAT;

  // Part A: Sales/Output
  doc.setFontSize(11);
  doc.text("PART A: OUTPUT TAX (Sales)", 20, yPos);
  yPos += 8;

  const outputData = [
    [
      "1",
      "Taxable Sales (13%)",
      formatCurrency(metrics.totalRevenue),
      formatCurrency(outputVAT),
    ],
    ["2", "Zero-Rated Sales", formatCurrency(0), formatCurrency(0)],
    ["3", "Exempt Sales", formatCurrency(0), formatCurrency(0)],
    ["4", "Total Output VAT (A)", "", formatCurrency(outputVAT)],
  ];

  autoTable(doc, {
    startY: yPos,
    head: [["S.N.", "Particulars", "Taxable Amount", "VAT Amount"]],
    body: outputData,
    theme: "grid",
    headStyles: { fillColor: [26, 35, 126], textColor: 255, fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 4 },
    columnStyles: {
      0: { cellWidth: 15, halign: "center" },
      2: { halign: "right" },
      3: { halign: "right" },
    },
  });

  yPos = (doc as any).lastAutoTable.finalY + 15;

  // Part B: Purchases/Input
  doc.setTextColor(26, 35, 126);
  doc.setFont("helvetica", "bold");
  doc.text("PART B: INPUT TAX (Purchases)", 20, yPos);
  yPos += 8;

  const inputData = [
    [
      "5",
      "Taxable Purchases (13%)",
      formatCurrency(metrics.totalExpenses),
      formatCurrency(inputVAT),
    ],
    ["6", "Capital Goods Purchases", formatCurrency(0), formatCurrency(0)],
    ["7", "Import Purchases", formatCurrency(0), formatCurrency(0)],
    ["8", "Total Input VAT (B)", "", formatCurrency(inputVAT)],
  ];

  autoTable(doc, {
    startY: yPos,
    head: [["S.N.", "Particulars", "Taxable Amount", "VAT Amount"]],
    body: inputData,
    theme: "grid",
    headStyles: { fillColor: [26, 35, 126], textColor: 255, fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 4 },
    columnStyles: {
      0: { cellWidth: 15, halign: "center" },
      2: { halign: "right" },
      3: { halign: "right" },
    },
  });

  yPos = (doc as any).lastAutoTable.finalY + 15;

  // Part C: Net VAT
  doc.text("PART C: NET VAT PAYABLE/REFUNDABLE", 20, yPos);
  yPos += 8;

  const netData = [
    ["9", "Net VAT Payable (A - B)", formatCurrency(netVAT > 0 ? netVAT : 0)],
    [
      "10",
      "VAT Refund Claimed",
      formatCurrency(netVAT < 0 ? Math.abs(netVAT) : 0),
    ],
    ["11", "Previous Period Credit", formatCurrency(0)],
    ["12", "Amount Payable to IRD", formatCurrency(netVAT > 0 ? netVAT : 0)],
  ];

  autoTable(doc, {
    startY: yPos,
    head: [["S.N.", "Particulars", "Amount (NPR)"]],
    body: netData,
    theme: "grid",
    headStyles: { fillColor: [26, 35, 126], textColor: 255, fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 4 },
    columnStyles: {
      0: { cellWidth: 15, halign: "center" },
      2: { halign: "right" },
    },
  });

  yPos = (doc as any).lastAutoTable.finalY + 20;

  // Declaration
  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  doc.setFont("helvetica", "normal");
  doc.text(
    "I hereby declare that the information provided above is true and correct to the best of my knowledge.",
    20,
    yPos
  );

  yPos += 15;
  addSignatureSection(doc, yPos, config);
  addFooter(doc, "VAT Return Form");

  return doc;
};

// TDS Deposit Statement
export const generateTDSStatement = (
  metrics: FinancialMetrics,
  config: OfficialDocumentConfig
): jsPDF => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  let yPos = addOfficialHeader(
    doc,
    "TDS DEPOSIT STATEMENT",
    "Tax Deducted at Source Report",
    config
  );
  yPos = addBusinessInfoSection(doc, yPos, config);

  doc.setTextColor(26, 35, 126);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(`Statement Period: ${config.period || "Monthly"}`, 20, yPos);
  yPos += 15;

  // TDS Deductions table
  const tdsCategories = [
    {
      category: "Salary & Wages",
      rate: "1% - 36%",
      amount: metrics.totalExpenses * 0.4,
      tds: metrics.totalExpenses * 0.4 * 0.15,
    },
    {
      category: "Rent Payment",
      rate: "10%",
      amount: metrics.totalExpenses * 0.1,
      tds: metrics.totalExpenses * 0.01,
    },
    {
      category: "Professional Services",
      rate: "15%",
      amount: metrics.totalExpenses * 0.15,
      tds: metrics.totalExpenses * 0.0225,
    },
    {
      category: "Contract Payments",
      rate: "1.5%",
      amount: metrics.totalExpenses * 0.2,
      tds: metrics.totalExpenses * 0.003,
    },
    { category: "Interest on Deposits", rate: "5%", amount: 0, tds: 0 },
  ];

  const totalTDS = tdsCategories.reduce((sum, cat) => sum + cat.tds, 0);

  const tdsData = tdsCategories.map((cat, idx) => [
    (idx + 1).toString(),
    cat.category,
    cat.rate,
    formatCurrency(cat.amount),
    formatCurrency(cat.tds),
  ]);

  tdsData.push(["", "TOTAL TDS DEDUCTED", "", "", formatCurrency(totalTDS)]);

  autoTable(doc, {
    startY: yPos,
    head: [
      [
        "S.N.",
        "Nature of Payment",
        "TDS Rate",
        "Payment Amount",
        "TDS Deducted",
      ],
    ],
    body: tdsData,
    theme: "grid",
    headStyles: { fillColor: [26, 35, 126], textColor: 255, fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 4 },
    columnStyles: {
      0: { cellWidth: 15, halign: "center" },
      3: { halign: "right" },
      4: { halign: "right" },
    },
    didParseCell: function (data) {
      if (data.row.index === tdsData.length - 1) {
        data.cell.styles.fontStyle = "bold";
        data.cell.styles.fillColor = [240, 240, 240];
      }
    },
  });

  yPos = (doc as any).lastAutoTable.finalY + 20;

  // Deposit Details
  doc.setTextColor(26, 35, 126);
  doc.setFont("helvetica", "bold");
  doc.text("TDS Deposit Details", 20, yPos);
  yPos += 10;

  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.setFontSize(10);
  doc.text(`Total TDS to be Deposited: ${formatCurrency(totalTDS)}`, 25, yPos);
  yPos += 8;
  doc.text("Deposit Bank: _________________________", 25, yPos);
  yPos += 8;
  doc.text("Deposit Date: _________________________", 25, yPos);
  yPos += 8;
  doc.text("Challan/Voucher No: ___________________", 25, yPos);

  yPos += 20;
  addSignatureSection(doc, yPos, config);
  addFooter(doc, "TDS Statement");

  return doc;
};

// Annual Tax Return Summary
export const generateAnnualTaxReturn = (
  metrics: FinancialMetrics,
  config: OfficialDocumentConfig
): jsPDF => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  let yPos = addOfficialHeader(
    doc,
    "ANNUAL TAX RETURN SUMMARY",
    "Income Tax Computation Statement",
    config
  );
  yPos = addBusinessInfoSection(doc, yPos, config);

  const netProfit = metrics.totalRevenue - metrics.totalExpenses;
  const taxableIncome = netProfit > 0 ? netProfit : 0;

  // Business income tax rate for Nepal (25% for companies, different for others)
  const taxRate = 0.25;
  const taxPayable = taxableIncome * taxRate;

  // Part 1: Income Computation
  doc.setTextColor(26, 35, 126);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("PART 1: INCOME COMPUTATION", 20, yPos);
  yPos += 10;

  const incomeData = [
    ["1", "Gross Business Revenue", formatCurrency(metrics.totalRevenue)],
    ["2", "Less: Cost of Goods Sold", formatCurrency(0)],
    ["3", "Gross Profit", formatCurrency(metrics.totalRevenue)],
    ["4", "Less: Operating Expenses", formatCurrency(metrics.totalExpenses)],
    ["5", "Net Business Income", formatCurrency(netProfit)],
    ["6", "Add: Other Income", formatCurrency(0)],
    ["7", "Total Income", formatCurrency(netProfit)],
  ];

  autoTable(doc, {
    startY: yPos,
    head: [["S.N.", "Particulars", "Amount (NPR)"]],
    body: incomeData,
    theme: "grid",
    headStyles: { fillColor: [26, 35, 126], textColor: 255, fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 4 },
    columnStyles: {
      0: { cellWidth: 15, halign: "center" },
      2: { halign: "right" },
    },
  });

  yPos = (doc as any).lastAutoTable.finalY + 15;

  // Part 2: Tax Computation
  doc.setTextColor(26, 35, 126);
  doc.setFont("helvetica", "bold");
  doc.text("PART 2: TAX COMPUTATION", 20, yPos);
  yPos += 10;

  const taxData = [
    ["8", "Taxable Income (from Part 1)", formatCurrency(taxableIncome)],
    ["9", "Less: Tax Exemptions/Deductions", formatCurrency(0)],
    ["10", "Net Taxable Income", formatCurrency(taxableIncome)],
    ["11", `Income Tax @ 25%`, formatCurrency(taxPayable)],
    [
      "12",
      "Less: TDS Already Paid",
      formatCurrency(metrics.totalExpenses * 0.05),
    ],
    ["13", "Less: Advance Tax Paid", formatCurrency(0)],
    [
      "14",
      "Net Tax Payable/(Refundable)",
      formatCurrency(Math.max(0, taxPayable - metrics.totalExpenses * 0.05)),
    ],
  ];

  autoTable(doc, {
    startY: yPos,
    head: [["S.N.", "Particulars", "Amount (NPR)"]],
    body: taxData,
    theme: "grid",
    headStyles: { fillColor: [26, 35, 126], textColor: 255, fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 4 },
    columnStyles: {
      0: { cellWidth: 15, halign: "center" },
      2: { halign: "right" },
    },
    didParseCell: function (data) {
      if (data.row.index === taxData.length - 1) {
        data.cell.styles.fontStyle = "bold";
        data.cell.styles.fillColor = [240, 240, 240];
      }
    },
  });

  yPos = (doc as any).lastAutoTable.finalY + 20;

  // Declaration
  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  doc.setFont("helvetica", "normal");
  const declaration =
    "I/We hereby declare that the information provided in this return is true, correct and complete to the best of my/our knowledge and belief, and that no income has been concealed.";
  const lines = doc.splitTextToSize(declaration, pageWidth - 40);
  doc.text(lines, 20, yPos);

  yPos += 20;
  addSignatureSection(doc, yPos, config);
  addFooter(doc, "Annual Tax Return");

  return doc;
};

// Profit & Loss Statement
export const generateProfitLossStatement = (
  metrics: FinancialMetrics,
  config: OfficialDocumentConfig
): jsPDF => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  let yPos = addOfficialHeader(
    doc,
    "PROFIT & LOSS STATEMENT",
    `For the Fiscal Year ${config.fiscalYear || getCurrentFiscalYear()}`,
    config
  );
  yPos = addBusinessInfoSection(doc, yPos, config);

  // Revenue Section
  doc.setTextColor(26, 35, 126);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("REVENUE", 20, yPos);
  yPos += 10;

  const revenueData =
    metrics.revenueCategories.length > 0
      ? metrics.revenueCategories.map((cat, idx) => [
          (idx + 1).toString(),
          cat.name,
          formatCurrency(cat.amount),
        ])
      : [["1", "Sales Revenue", formatCurrency(metrics.totalRevenue)]];

  revenueData.push(["", "Total Revenue", formatCurrency(metrics.totalRevenue)]);

  autoTable(doc, {
    startY: yPos,
    head: [["S.N.", "Particulars", "Amount (NPR)"]],
    body: revenueData,
    theme: "grid",
    headStyles: { fillColor: [34, 197, 94], textColor: 255, fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 4 },
    columnStyles: {
      0: { cellWidth: 15, halign: "center" },
      2: { halign: "right" },
    },
    didParseCell: function (data) {
      if (data.row.index === revenueData.length - 1) {
        data.cell.styles.fontStyle = "bold";
        data.cell.styles.fillColor = [220, 252, 231];
      }
    },
  });

  yPos = (doc as any).lastAutoTable.finalY + 15;

  // Expenses Section
  doc.setTextColor(26, 35, 126);
  doc.setFont("helvetica", "bold");
  doc.text("EXPENSES", 20, yPos);
  yPos += 10;

  const expenseData =
    metrics.expenseCategories.length > 0
      ? metrics.expenseCategories.map((cat, idx) => [
          (idx + 1).toString(),
          cat.name,
          formatCurrency(cat.amount),
        ])
      : [["1", "Operating Expenses", formatCurrency(metrics.totalExpenses)]];

  expenseData.push([
    "",
    "Total Expenses",
    formatCurrency(metrics.totalExpenses),
  ]);

  autoTable(doc, {
    startY: yPos,
    head: [["S.N.", "Particulars", "Amount (NPR)"]],
    body: expenseData,
    theme: "grid",
    headStyles: { fillColor: [239, 68, 68], textColor: 255, fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 4 },
    columnStyles: {
      0: { cellWidth: 15, halign: "center" },
      2: { halign: "right" },
    },
    didParseCell: function (data) {
      if (data.row.index === expenseData.length - 1) {
        data.cell.styles.fontStyle = "bold";
        data.cell.styles.fillColor = [254, 226, 226];
      }
    },
  });

  yPos = (doc as any).lastAutoTable.finalY + 15;

  // Net Profit/Loss
  const netProfit = metrics.totalRevenue - metrics.totalExpenses;
  const isProfit = netProfit >= 0;

  doc.setFillColor(
    isProfit ? 34 : 239,
    isProfit ? 197 : 68,
    isProfit ? 94 : 68
  );
  doc.roundedRect(20, yPos, pageWidth - 40, 25, 3, 3, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(
    `NET ${isProfit ? "PROFIT" : "LOSS"}:  ${formatCurrency(
      Math.abs(netProfit)
    )}`,
    pageWidth / 2,
    yPos + 16,
    { align: "center" }
  );

  yPos += 40;
  addSignatureSection(doc, yPos, config);
  addFooter(doc, "Profit & Loss Statement");

  return doc;
};

// Balance Sheet
export const generateBalanceSheet = (
  metrics: FinancialMetrics,
  config: OfficialDocumentConfig
): jsPDF => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  let yPos = addOfficialHeader(
    doc,
    "BALANCE SHEET",
    `As at ${formatDate(new Date())}`,
    config
  );
  yPos = addBusinessInfoSection(doc, yPos, config);

  const netProfit = metrics.totalRevenue - metrics.totalExpenses;

  // Assets
  doc.setTextColor(26, 35, 126);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("ASSETS", 20, yPos);
  yPos += 10;

  const currentAssets = metrics.totalRevenue * 0.6; // Simplified estimation
  const fixedAssets = metrics.totalRevenue * 0.3;
  const totalAssets = currentAssets + fixedAssets;

  const assetData = [
    ["", "CURRENT ASSETS", ""],
    ["1", "Cash and Bank Balances", formatCurrency(currentAssets * 0.3)],
    ["2", "Accounts Receivable", formatCurrency(currentAssets * 0.4)],
    ["3", "Inventory", formatCurrency(currentAssets * 0.3)],
    ["", "Total Current Assets", formatCurrency(currentAssets)],
    ["", "FIXED ASSETS", ""],
    ["4", "Property, Plant & Equipment", formatCurrency(fixedAssets * 0.7)],
    ["5", "Less: Accumulated Depreciation", formatCurrency(fixedAssets * 0.2)],
    ["6", "Intangible Assets", formatCurrency(fixedAssets * 0.1)],
    ["", "Total Fixed Assets", formatCurrency(fixedAssets)],
    ["", "TOTAL ASSETS", formatCurrency(totalAssets)],
  ];

  autoTable(doc, {
    startY: yPos,
    head: [["S.N.", "Particulars", "Amount (NPR)"]],
    body: assetData,
    theme: "grid",
    headStyles: { fillColor: [26, 35, 126], textColor: 255, fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 3 },
    columnStyles: {
      0: { cellWidth: 15, halign: "center" },
      2: { halign: "right" },
    },
    didParseCell: function (data) {
      const rowData = data.row.raw as string[];
      if (rowData && rowData[0] === "" && data.section === "body") {
        data.cell.styles.fontStyle = "bold";
        if (rowData[1] && rowData[1].startsWith("TOTAL")) {
          data.cell.styles.fillColor = [240, 240, 240];
        }
      }
    },
  });

  yPos = (doc as any).lastAutoTable.finalY + 15;

  // Liabilities & Equity
  doc.setTextColor(26, 35, 126);
  doc.setFont("helvetica", "bold");
  doc.text("LIABILITIES & EQUITY", 20, yPos);
  yPos += 10;

  const currentLiabilities = metrics.totalExpenses * 0.4;
  const longTermLiabilities = metrics.totalExpenses * 0.2;
  const equity = totalAssets - currentLiabilities - longTermLiabilities;

  const liabilityData = [
    ["", "CURRENT LIABILITIES", ""],
    ["1", "Accounts Payable", formatCurrency(currentLiabilities * 0.5)],
    ["2", "Short-term Loans", formatCurrency(currentLiabilities * 0.3)],
    ["3", "Taxes Payable", formatCurrency(currentLiabilities * 0.2)],
    ["", "Total Current Liabilities", formatCurrency(currentLiabilities)],
    ["", "LONG-TERM LIABILITIES", ""],
    ["4", "Bank Loans", formatCurrency(longTermLiabilities)],
    [
      "",
      "Total Liabilities",
      formatCurrency(currentLiabilities + longTermLiabilities),
    ],
    ["", "EQUITY", ""],
    ["5", "Share Capital", formatCurrency(equity * 0.7)],
    ["6", "Retained Earnings", formatCurrency(equity * 0.3)],
    ["", "Total Equity", formatCurrency(equity)],
    ["", "TOTAL LIABILITIES & EQUITY", formatCurrency(totalAssets)],
  ];

  autoTable(doc, {
    startY: yPos,
    head: [["S.N.", "Particulars", "Amount (NPR)"]],
    body: liabilityData,
    theme: "grid",
    headStyles: { fillColor: [26, 35, 126], textColor: 255, fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 3 },
    columnStyles: {
      0: { cellWidth: 15, halign: "center" },
      2: { halign: "right" },
    },
    didParseCell: function (data) {
      const rowData = data.row.raw as string[];
      if (rowData && rowData[0] === "" && data.section === "body") {
        data.cell.styles.fontStyle = "bold";
        if (
          rowData[1] &&
          (rowData[1].startsWith("TOTAL") || rowData[1].startsWith("Total"))
        ) {
          data.cell.styles.fillColor = [240, 240, 240];
        }
      }
    },
  });

  yPos = (doc as any).lastAutoTable.finalY + 20;
  addSignatureSection(doc, yPos, config);
  addFooter(doc, "Balance Sheet");

  return doc;
};

// Bank Loan Application Form
export const generateBankLoanApplication = (
  metrics: FinancialMetrics,
  config: OfficialDocumentConfig
): jsPDF => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  let yPos = addOfficialHeader(
    doc,
    "BUSINESS LOAN APPLICATION",
    "Financial Summary for Banking Purposes",
    config
  );
  yPos = addBusinessInfoSection(doc, yPos, config);

  // Loan Request Details
  doc.setTextColor(26, 35, 126);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("LOAN REQUEST DETAILS", 20, yPos);
  yPos += 10;

  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.setFontSize(10);

  doc.text("Loan Amount Requested: NPR _________________________", 25, yPos);
  yPos += 8;
  doc.text("Loan Purpose: ________________________________________", 25, yPos);
  yPos += 8;
  doc.text("Preferred Tenure: _______ months", 25, yPos);
  yPos += 15;

  // Financial Summary
  doc.setTextColor(26, 35, 126);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("FINANCIAL SUMMARY", 20, yPos);
  yPos += 10;

  const profitMargin =
    metrics.totalRevenue > 0
      ? (
          ((metrics.totalRevenue - metrics.totalExpenses) /
            metrics.totalRevenue) *
          100
        ).toFixed(1)
      : "0.0";

  const financialData = [
    ["Annual Revenue", formatCurrency(metrics.totalRevenue)],
    ["Annual Expenses", formatCurrency(metrics.totalExpenses)],
    [
      "Net Annual Profit",
      formatCurrency(metrics.totalRevenue - metrics.totalExpenses),
    ],
    ["Profit Margin", `${profitMargin}%`],
    ["Average Monthly Revenue", formatCurrency(metrics.totalRevenue / 12)],
    ["Financial Health Score", `${metrics.financialHealthScore}/100`],
    ["Documents Verified", `${metrics.documentCount} documents`],
  ];

  autoTable(doc, {
    startY: yPos,
    head: [["Financial Metric", "Value"]],
    body: financialData,
    theme: "grid",
    headStyles: { fillColor: [26, 35, 126], textColor: 255, fontSize: 10 },
    styles: { fontSize: 10, cellPadding: 5 },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 80 },
      1: { halign: "right" },
    },
  });

  yPos = (doc as any).lastAutoTable.finalY + 15;

  // Cash Flow Analysis
  if (metrics.monthlyData.length > 0) {
    doc.setTextColor(26, 35, 126);
    doc.setFont("helvetica", "bold");
    doc.text("CASH FLOW TREND (Last 6 Months)", 20, yPos);
    yPos += 10;

    const cashFlowData = metrics.monthlyData
      .slice(-6)
      .map((m) => [
        m.month,
        formatCurrency(m.income),
        formatCurrency(m.expenses),
        formatCurrency(m.income - m.expenses),
      ]);

    autoTable(doc, {
      startY: yPos,
      head: [["Month", "Income", "Expenses", "Net Cash Flow"]],
      body: cashFlowData,
      theme: "grid",
      headStyles: { fillColor: [26, 35, 126], textColor: 255, fontSize: 9 },
      styles: { fontSize: 9, cellPadding: 4 },
      columnStyles: {
        1: { halign: "right" },
        2: { halign: "right" },
        3: { halign: "right" },
      },
    });

    yPos = (doc as any).lastAutoTable.finalY + 15;
  }

  // Certification
  doc.setDrawColor(26, 35, 126);
  doc.setLineWidth(0.5);
  doc.rect(20, yPos, pageWidth - 40, 30);

  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  doc.setFont("helvetica", "bold");
  doc.text("CERTIFICATION", 25, yPos + 10);
  doc.setFont("helvetica", "normal");
  doc.text(
    "This financial summary is generated based on actual documents uploaded to Arthiq platform.",
    25,
    yPos + 18
  );
  doc.text(
    "Data accuracy depends on the quality and completeness of source documents provided.",
    25,
    yPos + 25
  );

  yPos += 40;
  addSignatureSection(doc, yPos, config);
  addFooter(doc, "Bank Loan Application");

  return doc;
};

// Social Security Fund (SSF) Report
export const generateSSFReport = (
  metrics: FinancialMetrics,
  config: OfficialDocumentConfig
): jsPDF => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  let yPos = addOfficialHeader(
    doc,
    "SOCIAL SECURITY FUND REPORT",
    "Employee Contribution Statement",
    config
  );
  yPos = addBusinessInfoSection(doc, yPos, config);

  doc.setTextColor(26, 35, 126);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(`Contribution Period: ${config.period || "Monthly"}`, 20, yPos);
  yPos += 15;

  // Estimated payroll (40% of expenses assumed as salary)
  const estimatedPayroll = metrics.totalExpenses * 0.4;
  const employerContribution = estimatedPayroll * 0.2; // 20% employer contribution
  const employeeContribution = estimatedPayroll * 0.11; // 11% employee contribution
  const totalContribution = employerContribution + employeeContribution;

  const ssfData = [
    ["1", "Total Gross Salary/Wages", formatCurrency(estimatedPayroll)],
    ["2", "Number of Employees", "___________"],
    ["3", "Employee Contribution (11%)", formatCurrency(employeeContribution)],
    ["4", "Employer Contribution (20%)", formatCurrency(employerContribution)],
    ["5", "Total SSF Contribution", formatCurrency(totalContribution)],
  ];

  autoTable(doc, {
    startY: yPos,
    head: [["S.N.", "Particulars", "Amount (NPR)"]],
    body: ssfData,
    theme: "grid",
    headStyles: { fillColor: [26, 35, 126], textColor: 255, fontSize: 10 },
    styles: { fontSize: 10, cellPadding: 5 },
    columnStyles: {
      0: { cellWidth: 15, halign: "center" },
      2: { halign: "right" },
    },
    didParseCell: function (data) {
      if (data.row.index === ssfData.length - 1) {
        data.cell.styles.fontStyle = "bold";
        data.cell.styles.fillColor = [240, 240, 240];
      }
    },
  });

  yPos = (doc as any).lastAutoTable.finalY + 20;

  // Deposit Details
  doc.setTextColor(26, 35, 126);
  doc.setFont("helvetica", "bold");
  doc.text("DEPOSIT DETAILS", 20, yPos);
  yPos += 10;

  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.setFontSize(10);
  doc.text("SSF Fund Code: _________________________", 25, yPos);
  yPos += 8;
  doc.text("Deposit Bank: _________________________", 25, yPos);
  yPos += 8;
  doc.text("Deposit Date: _________________________", 25, yPos);
  yPos += 8;
  doc.text("Transaction Reference: ________________", 25, yPos);

  yPos += 25;

  // Note
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(
    "Note: SSF contribution rates as per Social Security Act 2074 (2017)",
    20,
    yPos
  );
  doc.text(
    "Employer: 20% | Employee: 11% | Total: 31% of basic salary",
    20,
    yPos + 8
  );

  yPos += 25;
  addSignatureSection(doc, yPos, config);
  addFooter(doc, "SSF Report");

  return doc;
};

// Audit-Ready Financial Package
export const generateAuditPackage = (
  metrics: FinancialMetrics,
  insights: RegulationInsights | null,
  config: OfficialDocumentConfig
): jsPDF => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  let yPos = addOfficialHeader(
    doc,
    "AUDIT-READY FINANCIAL PACKAGE",
    "Comprehensive Financial Documentation",
    config
  );
  yPos = addBusinessInfoSection(doc, yPos, config);

  // Executive Summary
  doc.setTextColor(26, 35, 126);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("EXECUTIVE SUMMARY", 20, yPos);
  yPos += 10;

  const netProfit = metrics.totalRevenue - metrics.totalExpenses;
  const profitMargin =
    metrics.totalRevenue > 0
      ? ((netProfit / metrics.totalRevenue) * 100).toFixed(1)
      : "0.0";

  const summaryData = [
    ["Total Revenue", formatCurrency(metrics.totalRevenue)],
    ["Total Expenses", formatCurrency(metrics.totalExpenses)],
    ["Net Profit/(Loss)", formatCurrency(netProfit)],
    ["Profit Margin", `${profitMargin}%`],
    ["VAT Collected", formatCurrency(metrics.vatCollected)],
    ["Financial Health Score", `${metrics.financialHealthScore}/100`],
    [
      "Compliance Score",
      insights ? `${insights.summary.complianceScore}/100` : "N/A",
    ],
  ];

  autoTable(doc, {
    startY: yPos,
    head: [["Key Metric", "Value"]],
    body: summaryData,
    theme: "grid",
    headStyles: { fillColor: [26, 35, 126], textColor: 255, fontSize: 10 },
    styles: { fontSize: 10, cellPadding: 5 },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 80 },
      1: { halign: "right" },
    },
  });

  yPos = (doc as any).lastAutoTable.finalY + 15;

  // Documents Reviewed
  doc.setTextColor(26, 35, 126);
  doc.setFont("helvetica", "bold");
  doc.text("DOCUMENTS REVIEWED", 20, yPos);
  yPos += 10;

  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.setFontSize(10);
  doc.text(`Total Documents Processed: ${metrics.documentCount}`, 25, yPos);
  yPos += 8;
  doc.text(
    "Document Types: Bank Statements, Invoices, Receipts, Bills",
    25,
    yPos
  );
  yPos += 8;
  doc.text("Data Extraction: AI-powered with automated validation", 25, yPos);

  yPos += 15;

  // Monthly Performance
  if (metrics.monthlyData.length > 0) {
    doc.setTextColor(26, 35, 126);
    doc.setFont("helvetica", "bold");
    doc.text("MONTHLY PERFORMANCE", 20, yPos);
    yPos += 10;

    const monthlyTableData = metrics.monthlyData.map((m) => [
      m.month,
      formatCurrency(m.income),
      formatCurrency(m.expenses),
      formatCurrency(m.income - m.expenses),
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [["Month", "Revenue", "Expenses", "Net"]],
      body: monthlyTableData,
      theme: "grid",
      headStyles: { fillColor: [26, 35, 126], textColor: 255, fontSize: 9 },
      styles: { fontSize: 9, cellPadding: 4 },
      columnStyles: {
        1: { halign: "right" },
        2: { halign: "right" },
        3: { halign: "right" },
      },
    });

    yPos = (doc as any).lastAutoTable.finalY + 15;
  }

  // Add new page for compliance section
  doc.addPage();
  yPos = 20;

  // Compliance Status
  if (insights) {
    doc.setTextColor(26, 35, 126);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("COMPLIANCE STATUS", 20, yPos);
    yPos += 10;

    const complianceData = insights.taxObligations.map((tax) => [
      tax.type,
      tax.status.replace("_", " ").toUpperCase(),
      tax.description.substring(0, 40),
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [["Obligation", "Status", "Description"]],
      body: complianceData,
      theme: "grid",
      headStyles: { fillColor: [26, 35, 126], textColor: 255, fontSize: 9 },
      styles: { fontSize: 9, cellPadding: 4 },
    });

    yPos = (doc as any).lastAutoTable.finalY + 15;

    // Risks if any
    if (insights.risks.length > 0) {
      doc.setTextColor(26, 35, 126);
      doc.setFont("helvetica", "bold");
      doc.text("IDENTIFIED RISKS", 20, yPos);
      yPos += 10;

      const riskData = insights.risks
        .slice(0, 5)
        .map((risk) => [
          risk.severity.toUpperCase(),
          risk.title,
          risk.recommendation.substring(0, 40),
        ]);

      autoTable(doc, {
        startY: yPos,
        head: [["Severity", "Risk", "Recommendation"]],
        body: riskData,
        theme: "grid",
        headStyles: { fillColor: [239, 68, 68], textColor: 255, fontSize: 9 },
        styles: { fontSize: 9, cellPadding: 4 },
      });

      yPos = (doc as any).lastAutoTable.finalY + 20;
    }
  }

  // Auditor Notes Section
  doc.setTextColor(26, 35, 126);
  doc.setFont("helvetica", "bold");
  doc.text("AUDITOR NOTES", 20, yPos);
  yPos += 10;

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  for (let i = 0; i < 8; i++) {
    doc.line(20, yPos + i * 8, pageWidth - 20, yPos + i * 8);
  }

  yPos += 70;
  addSignatureSection(doc, yPos, config);
  addFooter(doc, "Audit Package");

  return doc;
};
